### ISSUE TITLE
Comments replaceMore gives an error

### ISSUE THREAD

**Issue by Ivaskuu** [draw-dev/DRAW#137] opened 2019-04-02 10:20 UTC
Hi!

I was trying to replace all the 'replace more' comments in a CommentForest, but somehow it didn't seem to work and threw this error:
```
E/flutter (28141): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter '_comments' was called on null.
E/flutter (28141): Receiver: null
E/flutter (28141): Tried calling: _comments
E/flutter (28141): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
E/flutter (28141): #1      CommentForest._insertComment (package:draw/src/models/comment_forest.dart:53:22)
E/flutter (28141): #2      List.forEach (dart:core/runtime/libarray.dart:106:8)
E/flutter (28141): #3      CommentForest.replaceMore (package:draw/src/models/comment_forest.dart:125:19)
```

This is the code I was using:
```
Submission post = await reddit.submission(id: id).populate();
await post.refresh();
await post.refreshComments();
await post.comments.replaceMore();
```

**Comment by StefanLobbenmeier** [comment] 2019-04-02 10:42
Hi :) 

Can you give the id of a submission where this happens? Or does it happen with every submission?

**Comment by StefanLobbenmeier** [comment] 2019-04-02 10:49
Ok the issue seems to be here:


```
/// Returns the [CommentForest] representing the comments for this
  /// [Submission]. May be null (see [refreshComments]).
  CommentForest get comments => _comments;
```

But since you called refresh Comments it should not be null anymore.

**Comment by bkonyi** [comment] 2019-04-22 17:25
Sorry for the delay on this. I'll take a look ASAP.

**Comment by bkonyi** [comment] 2019-05-17 22:35
@StefanLobbenmeier, was this resolved by your PR or was this another failure?

**Comment by StefanLobbenmeier** [comment] 2019-05-18 08:02
It was not resolved by my PR, at least not intentionally.

**Comment by bkonyi** [comment] 2019-05-20 14:19
> It was not resolved by my PR, at least not intentionally.

I didn't think so, but figured I'd check. Were you ever able to reproduce this with a specific submission? If so, can you post it here so I can take a look?

**Comment by bkonyi** [comment] 2019-07-08 20:59
Quick bump on this issue. @StefanLobbenmeier, have you been able to reproduce? Otherwise I'll close this for now.

**Comment by StefanLobbenmeier** [comment] 2019-07-14 16:43
Sorry, I have been gone for some time, but I will hopefully be more active again now :) I did not attempt to reproduce, I was also hoping for @Ivaskuu to provide a specific submission

**Comment by bkonyi** [comment] 2019-07-15 17:25
> Sorry, I have been gone for some time, but I will hopefully be more active again now :) I did not attempt to reproduce, I was also hoping for @Ivaskuu to provide a specific submission

Not a problem, just figured I'd check! I think I'm going to close this for now, but if someone runs into this error again feel free to reopen with reproduction steps.

**Closed by bkonyi** 2019-07-15 17:25 UTC
